In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("/content/Bangalore_AQI_Dataset.csv")
data

           City      Date  AQI  PM2.5   PM10    NO2    SO2    CO     O3
0     Bangalore  01/01/18   68  37.40  73.44  56.44  77.52  0.71  64.60
1     Bangalore  02/01/18   76  41.80  82.08  63.08  86.64  0.80  72.20
2     Bangalore  03/01/18   70  38.50  75.60  58.10  79.80  0.74  66.50
3     Bangalore  04/01/18   78  42.90  84.24  64.74  88.92  0.82  74.10
4     Bangalore  05/01/18   82  45.10  88.56  68.06  93.48  0.86  77.90
...         ...       ...  ...    ...    ...    ...    ...   ...    ...
2551  Bangalore  27/12/24   54  29.70  58.32  44.82  61.56  0.57  51.30
2552  Bangalore  28/12/24   57  31.35  61.56  47.31  64.98  0.60  54.15
2553  Bangalore  29/12/24   70  38.50  75.60  58.10  79.80  0.74  66.50
2554  Bangalore  30/12/24   62  34.10  66.96  51.46  70.68  0.65  58.90
2555  Bangalore  31/12/24   65  35.75  70.20  53.95  74.10  0.68  61.75

[2556 rows x 9 columns]

In [3]:
data.columns

Index(['City', 'Date', 'AQI', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3'], dtype='object')

In [4]:
data.isna().sum()

City     0
Date     0
AQI      0
PM2.5    0
PM10     0
NO2      0
SO2      0
CO       0
O3       0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(0)

In [6]:
data.sample(3)

           City      Date  AQI  PM2.5    PM10    NO2     SO2    CO      O3
268   Bangalore  26/09/18   81  44.55   87.48  67.23   92.34  0.85   76.95
2083  Bangalore  16/09/23   40  22.00   43.20  33.20   45.60  0.42   38.00
1530  Bangalore  12/03/22  108  59.40  116.64  89.64  123.12  1.13  102.60

In [7]:
data=data.drop(columns=['City','Date'])

In [8]:
data.head(2)

   AQI  PM2.5   PM10    NO2    SO2    CO    O3
0   68   37.4  73.44  56.44  77.52  0.71  64.6
1   76   41.8  82.08  63.08  86.64  0.80  72.2

In [9]:
x=data.drop(columns=['AQI'])
y=data['AQI']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

In [12]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [13]:
model.predict(x_test)

array([100.  ,  43.  ,  60.  ,  54.  ,  77.  ,  93.  ,  54.  , 108.  ,
        85.  ,  88.  ,  74.  ,  53.  , 106.  ,  86.  ,  95.  ,  38.  ,
        39.  ,  71.  , 106.  ,  52.  ,  47.  ,  42.  ,  71.  ,  54.  ,
        57.  ,  71.  , 100.  ,  87.  ,  48.  ,  57.  ,  73.  ,  91.  ,
        61.  , 122.  ,  71.  ,  89.  ,  48.  ,  93.  ,  88.  ,  96.  ,
       104.  ,  67.  ,  76.  ,  48.  , 119.  , 108.  ,  47.  , 125.  ,
        51.  ,  62.  ,  78.  ,  65.  ,  59.  ,  79.  ,  96.  ,  53.  ,
        94.  ,  93.  ,  58.  ,  53.  ,  75.  ,  55.  ,  51.  ,  43.  ,
       111.  , 129.93, 144.  ,  57.  ,  76.  ,  57.  ,  59.  , 112.  ,
        74.  , 122.  ,  40.  ,  38.  ,  74.  ,  60.  , 100.  ,  50.  ,
        95.  ,  94.  ,  69.  ,  66.  , 110.  , 103.  ,  86.  ,  97.  ,
        60.  ,  72.  ,  95.  ,  91.  ,  46.  ,  68.  ,  81.  ,  51.  ,
        79.  ,  44.  ,  74.  , 106.  ,  56.  , 123.95,  61.  ,  40.  ,
        99.  ,  55.  ,  68.  ,  64.  ,  77.  ,  84.  ,  76.  , 101.  ,
        44.  ,  99.  ,  74.  , 100.  , 119.  ,  79.  , 144.26,  87.  ,
        70.  ,  68.  ,  65.  ,  88.  ,  65.  ,  46.  ,  91.  ,  62.  ,
        77.  ,  83.  , 129.93,  90.  , 140.82,  70.  , 101.  ,  65.  ,
        45.  ,  42.  ,  82.  , 106.  ,  53.  ,  93.  ,  61.  ,  87.  ,
        69.  ,  85.  , 114.99, 106.  ,  95.  ,  96.  ,  81.  ,  71.  ,
       122.  , 112.  ,  48.  ,  80.  ,  43.  ,  89.  ,  45.  ,  46.  ,
        57.  ,  74.  ,  41.  ,  49.  ,  43.  ,  51.  ,  40.  ,  58.  ,
        67.  ,  62.  ,  86.  ,  93.  ,  52.  ,  82.  ,  68.  ,  58.  ,
        57.  ,  41.  , 106.  , 108.  ,  41.  ,  74.  ,  42.  , 100.  ,
        43.  ,  58.  ,  98.  ,  91.  ,  55.  ,  83.  , 101.  , 160.21,
        51.  ,  92.  ,  73.  ,  93.  ,  67.  , 119.  ,  46.  , 130.74,
        57.  , 102.  ,  60.  ,  65.  ,  55.  ,  55.  ,  78.  ,  63.  ,
       119.  ,  57.  ,  47.  ,  78.  ,  89.  ,  47.  ,  49.  ,  65.  ,
        84.  ,  50.  ,  81.  ,  55.  ,  54.  ,  96.  ,  58.  ,  79.  ,
        90.  ,  99.  ,  45.  ,  43.  , 103.  ,  45.  ,  46.  ,  78.  ,
       148.06, 116.  ,  95.  ,  51.  ,  76.  ,  86.  ,  42.  ,  56.  ,
        52.  , 116.  ,  92.  ,  53.  ,  81.  ,  45.  ,  84.  ,  68.  ,
        48.  ,  56.  ,  63.  ,  82.  , 112.  ,  88.  ,  34.  , 127.  ,
        55.  ,  92.  , 109.  ,  39.  ,  59.  ,  65.  ,  48.  ,  84.  ,
        50.  ,  65.  ,  65.  ,  56.  ,  97.  ,  54.  ,  57.  ,  52.  ,
        96.  ,  54.  ,  54.  ,  52.  ,  41.  ,  45.  ,  65.  ,  38.  ,
        61.  ,  65.  ,  61.  ,  64.  ,  74.  ,  66.  ,  53.  ,  80.  ,
        96.  ,  59.  ,  76.  , 103.  ,  54.  ,  63.  ,  81.  ,  49.  ,
        42.  ,  65.  , 163.89,  60.  ,  79.  ,  62.  ,  86.  ,  40.  ,
       111.  , 104.  ,  58.  , 109.  ,  59.  ,  93.  ,  64.  , 134.99,
        68.  ,  73.  , 111.  ,  61.  ,  88.  ,  84.  ,  73.  ,  89.  ,
        55.  ,  38.  ,  79.  , 122.  ,  55.  ,  44.  ,  88.  ,  61.  ,
        85.  ,  56.  ,  56.  ,  63.  ,  95.  ,  64.  , 106.  , 119.  ,
        73.  ,  77.  ,  54.  ,  41.  ,  57.  ,  48.  , 103.  ,  43.  ,
        74.  ,  76.  ,  63.  ,  55.  ,  89.  ,  56.  ,  38.  ,  55.  ,
        66.  ,  45.  ,  60.  ,  77.  ,  57.  ,  83.  ,  97.  ,  56.  ,
        57.  ,  93.  , 104.  ,  64.  ,  51.  , 113.  ,  82.  , 167.87,
        42.  , 148.06,  57.  , 114.99,  94.  ,  67.  ,  59.  ,  40.  ,
        48.  ,  36.  , 132.  ,  95.  , 177.83,  60.  ,  71.  ,  59.  ,
        93.  , 150.77,  85.  ,  62.  ,  99.  , 108.  ,  90.  ,  98.  ,
        76.  ,  55.  ,  94.  ,  48.  ,  96.  , 104.  ,  60.  , 142.9 ,
        88.  ,  63.  ,  48.  ,  70.  ,  67.  ,  50.  ,  98.  ,  88.  ,
        84.  ,  50.  ,  78.  ,  76.  ,  36.  ,  54.  ,  56.  ,  65.  ,
        34.  ,  52.  ,  56.  ,  62.  ,  53.  ,  61.  ,  57.  ,  84.  ,
       104.  , 112.  ,  46.  ,  52.  , 106.  ,  45.  ,  81.  ,  74.  ,
        53.  ,  42.  ,  65.  ,  93.  ,  76.  ,  50.  ,  57.  ,  65.  ,
        64.  ,  72.  ,  63.  ,  77.  ,  75.  ,  40.  ,  66.  ,  58.  ,
        44.  ,  65.  ,  84.  , 105.  ,  47.  ,  73.  , 113.  ,  60.  ,
        93.  ,  58.  ,  73.  ,  65.  ,  77.  ,  82.  ,  79.  ,  62.  ,
       105.  ,  82.  ,  76.  ,  66.  , 104.  ,  48.  ,  66.  ,  73.  ,
        53.  ,  73.  ,  54.  , 106.  ,  96.  ,  65.  ,  54.  ,  40.  ,
        64.  ,  94.  ,  75.  ,  96.  , 107.  ,  84.  ,  43.  ,  54.  ,
       119.  ,  48.  ,  35.  , 123.95,  95.  ,  39.  ,  85.  ,  49.  ,
        51.  ,  53.  ,  58.  ,  55.  ,  52.  ,  85.  , 102.  ,  79.  ,
        58.  , 107.  ,  43.  ,  62.  ,  82.  , 114.  ,  88.  ,  75.  ])

In [14]:
model.score(x_test,y_test)

0.9999874147178984

In [15]:
model.predict([[31.35,61.56,47.31,64.98,0.60,54.15]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([57.])

In [16]:
model.predict([[37.40,73.44,56.44,77.52,0.71,64.60]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([68.])

In [17]:
import pickle
with open('model.pkl','wb') as files:
  pickle.dump(model,files)